# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ef10d62a19829611163517fcc5fe79c74c2a5a4205ea2080cf8e3cafac21705afc167242d0812013fa8dfe574b0d8fb6a23deabd59357a4913c4427e016967

test:
  secret_key_base: 148e99e982ae3c88cb0fe8747e931489d6187ead558d61517444167455839023a6f8defc610783447794518bd03417da46293743b2f31f70dd5985f4ca51c3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
